.build:template: &build_definition
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
  script:
    - /kaniko/executor
      --cache
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}
      --skip-unused-stages
      --use-new-run
  interruptible: true

.deploy:template: &deploy_definition
  stage: deploy
  image: registry.bi.group/public/kubectl:gitlab-1.0.0
  before_script:
    - mkdir -p ~/.kube
    - |
      cat << EOF > ~/.kube/config
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: $K8S_CERT_AUTHORITY
          server: $K8S_SERVER
        name: kubernetes
      contexts:
      - context:
          cluster: kubernetes
          namespace: $K8S_NAMESPACE
          user: gitlab-runner
        name: kubernetes
      current-context: kubernetes
      kind: Config
      preferences: {}
      users:
      - name: gitlab-runner
        user:
          client-certificate-data: $K8S_USER_CRT
          client-key-data: $K8S_USER_KEY
      EOF
  script:
    - kubectl set image deployment/biagency-deployment biagency=${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHORT_SHA
    
.rules:staging:template: &rules_staging_definition
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.rules:production:template: &rules_production_definition
  rules:
    - if: $CI_COMMIT_BRANCH == "production"

build:biagency:production:
  <<: *build_definition
  <<: *rules_production_definition
    
deploy:production:
  <<: *deploy_definition
  <<: *rules_production_definition
  variables:
    K8S_CERT_AUTHORITY: $PRODUCTION_K8S_CERT_AUTHORITY
    K8S_SERVER: $PRODUCTION_K8S_SERVER
    K8S_NAMESPACE: $PRODUCTION_K8S_NAMESPACE
    K8S_USER_CRT: $PRODUCTION_K8S_USER_CRT
    K8S_USER_KEY: $PRODUCTION_K8S_USER_KEY
  tags:
    - production

